export const NOTIFICATION_TYPES = {
  MESSAGE: 'message',
  ADDED_TO_CONVERSATION: 'added_to_conversation',
  NEW_RIDE: 'new_ride',
  RIDE_UPDATE: 'ride_update',
  RIDE_CLAIMED: 'ride_claimed',
  RIDE_UNCLAIMED: 'ride_unclaimed',
  RIDE_COMPLETED: 'ride_completed',
  NEW_FAVOR: 'new_favor',
  FAVOR_UPDATE: 'favor_update',
  FAVOR_CLAIMED: 'favor_claimed',
  FAVOR_UNCLAIMED: 'favor_unclaimed',
  FAVOR_COMPLETED: 'favor_completed',
  COMPLETION_REMINDER: 'completion_reminder',
  QA_ACTIVITY: 'qa_activity',
  QA_QUESTION: 'qa_question',
  QA_ANSWER: 'qa_answer',
  REVIEW: 'review',
  REVIEW_RECEIVED: 'review_received',
  REVIEW_REMINDER: 'review_reminder',
  REVIEW_REQUEST: 'review_request',
  TOWN_HALL_POST: 'town_hall_post',
  TOWN_HALL_COMMENT: 'town_hall_comment',
  TOWN_HALL_REACTION: 'town_hall_reaction',
  ANNOUNCEMENT: 'announcement',
  ADMIN_ANNOUNCEMENT: 'admin_announcement',
  BROADCAST: 'broadcast',
  PENDING_APPROVAL: 'pending_approval',
  USER_APPROVED: 'user_approved',
  USER_REJECTED: 'user_rejected',
  OTHER: 'other',
} as const

export type NotificationType = typeof NOTIFICATION_TYPES[keyof typeof NOTIFICATION_TYPES]
