#!/bin/bash

# QA Report Generator for Naar's Cars iOS
# Usage: ./generate-report.sh <checkpoint-id> [--coverage]

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

CHECKPOINT_ID="$1"
INCLUDE_COVERAGE=false

if [[ "$2" == "--coverage" ]]; then
    INCLUDE_COVERAGE=true
fi

if [[ -z "$CHECKPOINT_ID" ]]; then
    echo "Usage: ./generate-report.sh <checkpoint-id> [--coverage]"
    exit 1
fi

REPORTS_DIR="QA/Reports"
REPORT_DIR="${REPORTS_DIR}/${CHECKPOINT_ID}"

if [[ ! -d "$REPORT_DIR" ]]; then
    echo "Error: No report found for checkpoint '$CHECKPOINT_ID'"
    echo "Run the checkpoint first: ./QA/Scripts/checkpoint.sh $CHECKPOINT_ID"
    exit 1
fi

echo -e "${BLUE}Generating detailed report for ${CHECKPOINT_ID}...${NC}"

# Find the most recent log file
LOG_FILE=$(ls -t "${REPORT_DIR}"/raw-output-*.log 2>/dev/null | head -1)

if [[ -z "$LOG_FILE" ]]; then
    LOG_FILE=$(ls -t "${REPORT_DIR}"/output-*.log 2>/dev/null | head -1)
fi

if [[ -z "$LOG_FILE" ]]; then
    echo "Error: No log file found in ${REPORT_DIR}"
    exit 1
fi

# Parse test results from log
TOTAL_TESTS=0
PASSED_TESTS=0
FAILED_TESTS=0
FAILURES=""

# Extract test counts (format varies by xcodebuild version)
if grep -q "Test Suite" "$LOG_FILE"; then
    # Parse xcpretty or raw output
    TOTAL_TESTS=$(grep -c "Test Case" "$LOG_FILE" 2>/dev/null || echo "0")
    PASSED_TESTS=$(grep -c "passed" "$LOG_FILE" 2>/dev/null || echo "0")
    FAILED_TESTS=$(grep -c "failed" "$LOG_FILE" 2>/dev/null || echo "0")
fi

# Extract failure details
if grep -q "FAILED" "$LOG_FILE"; then
    FAILURES=$(grep -A 5 "FAILED" "$LOG_FILE" | head -50)
fi

TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")

# Generate markdown report
REPORT_FILE="${REPORT_DIR}/detailed-report.md"

cat > "$REPORT_FILE" << EOF
# Detailed Checkpoint Report: ${CHECKPOINT_ID}

**Generated:** ${TIMESTAMP}
**Log Source:** $(basename "$LOG_FILE")

---

## Summary

| Metric | Value |
|--------|-------|
| Total Tests | ${TOTAL_TESTS} |
| Passed | ${PASSED_TESTS} |
| Failed | ${FAILED_TESTS} |

EOF

if [[ -n "$FAILURES" ]]; then
    cat >> "$REPORT_FILE" << EOF
## Failures

\`\`\`
${FAILURES}
\`\`\`

---

## Recommended Actions

1. Review each failure above
2. Identify root cause (test bug vs implementation bug)
3. Fix and re-run checkpoint
4. Do not proceed until all tests pass

EOF
else
    cat >> "$REPORT_FILE" << EOF
## Status

✅ **All tests passed!**

You may proceed to the next task.

EOF
fi

# Add coverage if requested
if $INCLUDE_COVERAGE; then
    echo -e "${YELLOW}Generating coverage report...${NC}"
    
    # Run with coverage enabled
    xcodebuild test \
        -project NaarsCars.xcodeproj \
        -scheme NaarsCars \
        -destination 'platform=iOS Simulator,name=iPhone 15' \
        -enableCodeCoverage YES \
        -resultBundlePath "${REPORT_DIR}/coverage.xcresult" \
        > /dev/null 2>&1 || true
    
    # Extract coverage with xcrun
    if [[ -d "${REPORT_DIR}/coverage.xcresult" ]]; then
        xcrun xccov view --report "${REPORT_DIR}/coverage.xcresult" > "${REPORT_DIR}/coverage.txt" 2>/dev/null || true
        
        cat >> "$REPORT_FILE" << EOF

## Code Coverage

\`\`\`
$(head -50 "${REPORT_DIR}/coverage.txt" 2>/dev/null || echo "Coverage data not available")
\`\`\`

EOF
    fi
fi

# Add flow mapping
cat >> "$REPORT_FILE" << EOF

---

## Flow Coverage

Reference: \`QA/FLOW-CATALOG.md\`

| Flow | Validated |
|------|-----------|
EOF

# Map checkpoint to flows
case $CHECKPOINT_ID in
    foundation-*)
        echo "| FLOW_FOUNDATION_001 | ⏳ Check manually |" >> "$REPORT_FILE"
        ;;
    auth-001)
        echo "| FLOW_AUTH_001 | ⏳ Check manually |" >> "$REPORT_FILE"
        ;;
    auth-002)
        echo "| FLOW_AUTH_002 | ⏳ Check manually |" >> "$REPORT_FILE"
        echo "| FLOW_AUTH_003 | ⏳ Check manually |" >> "$REPORT_FILE"
        ;;
    auth-003)
        echo "| FLOW_AUTH_004 | ⏳ Check manually |" >> "$REPORT_FILE"
        ;;
    profile-*)
        echo "| FLOW_PROFILE_001 | ⏳ Check manually |" >> "$REPORT_FILE"
        echo "| FLOW_PROFILE_002 | ⏳ Check manually |" >> "$REPORT_FILE"
        echo "| FLOW_PROFILE_003 | ⏳ Check manually |" >> "$REPORT_FILE"
        ;;
    ride-*)
        echo "| FLOW_RIDE_001-005 | ⏳ Check manually |" >> "$REPORT_FILE"
        ;;
    messaging-*)
        echo "| FLOW_MSG_001-003 | ⏳ Check manually |" >> "$REPORT_FILE"
        ;;
    *)
        echo "| (See flow catalog) | ⏳ Check manually |" >> "$REPORT_FILE"
        ;;
esac

echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "*Report generated by QA/Scripts/generate-report.sh*" >> "$REPORT_FILE"

echo -e "${GREEN}Report generated: ${REPORT_FILE}${NC}"
echo ""
cat "$REPORT_FILE"
